### ISSUE TITLE
Why restoring entity when it's getting created from EventSourcedRepo

### ISSUE THREAD

**Issue by eventsourcer** [MessageHandler/MessageHandler.Feedback#2]
Instead of restoring an entity when it's getting created (followed by Table storage calls), can't we move forward right away and flush? this might slightly increase performance.

![image](https://github.com/user-attachments/assets/de5bea4c-771b-4cdc-80aa-1824a9a5e5f6)

**Comment by yvesgoeleven** [comment]
No, that would not be possible. 

Your aggregate root is responsible for validating that a command may be acted upon, this requires historical knowledge of previous decissions (events). Therefore it must be restored prior to having it handle a command.

**Comment by eventsourcer** [comment]
Yes true I understand the command handling concern, but knowing there are no historical decisions for a brand new stream would simplify the object creation by only ensuring its ID doesn't exist already, instead of attempting to return the events (**select any** against event store might better fit in here instead of **select all**).

**Comment by yvesgoeleven** [comment]
I don't think select any is feasible, for 2 reasons:
- The underlying storage (Azure Table Storage) does not support it, I would still need to download at least the first result to see if there is anything on the stream.
- Even if it would, this would negatively effect all existing streams, as the code would still have to do a select all when the select any would yield true.

**Comment by yvesgoeleven** [comment]
That said, if you know that there is no stream yet, perhaps a Create overload that just does the tracking without a call to storage at all would be usefull?

Probably not, as a retry after flush would then result in an exception, while the Get approach can take care of idempotency as it has recorded the event.

**Comment by eventsourcer** [comment]
No that won't help I agree with your initial argument, ensuring entity isn't already in place is needed.

But here is my suggestion and I will leave that for you:
    1. any receiving create requests are followed by a check by ID prior to anything
    2. Any attempts of recreating with same order id, I would return a bad request in case it does exist
    3. this is idempotency on entity creation level which's different from event level per entity
    4. this requires exposing a Create(orderId) with above mentioned logic
    5. and a Get(orderId) is required to restore entity for all event appending requests, which makes these requests idempotent
    
Having this all said can only be achieved if the event store supports any or search by id, I haven't worked with Table Storage client so I am not really sure.

Otherwise, your way of approaching this is solid and my only concern here is the Get sends back OK when placing same order even if the stream exists.

**Comment by yvesgoeleven** [comment]
I have evaluated this option in the past, but there are a few issues with the suggestion to automatically return a bad request (or 409 conflict which is the one I had in mind)

1. The definition of idempotency. https://en.wikipedia.org/wiki/Idempotence

_Idempotence is the property of certain operations in mathematics and computer science whereby they can be applied multiple times  without changing the result beyond the initial application_ 

Returning a bad request on the second operation is changing the result of the initial application. 

If the first command returned an OK, then the second invocation of the same command should also return an OK, that is the expectation of idempotency.

2. Is the idea that the creation should always be idempotent. This is not the case. 

Aggregate Roots do not represent Entities to me, they represent Business Processes that realize Business Capabilities.

There are plenty of processes out there where you do want to respond differently to subsequent requests at the start of the process. Think of subsequent password change requests in a short timeframe, that might be an attempt at identity theft, which you want to detect, register as an event and react to, by e.g. notifying the account owner, instead of automatically returning a bad request.

Besides that, Azure storage does not support search by properties. It's just a KV store, all you can do is ask to return a range in the partition, either you get records or you don't. Secondary indexes are not supported.

**Comment by eventsourcer** [comment]
Driven by the very definition of idempotent operations, I tend to follow your approach.
