### ISSUE TITLE
Resending dead message from Dead-Letter gets handled by all handlers rather than intended subscription

### ISSUE THREAD

**Issue by eventsourcer** [MessageHandler/MessageHandler.Feedback#3]
Each subscriber polls for messages at its own pace and Azure does the job just fine, but arriving previously dead message is getting handled by all parties which potentially causes duplicates.

A typical example that I simulated on LearningPath is, prior confirming an order I deleted the search index (assuming Search service is down) and then confirming the order which is handled downstream persisting an order confirmation email which is then processed by the background thread, now attempting to resend dead message for the index subscription results in an additional email notification.

This is likewise true when Azure SQL is down which caused duplicate index documents.

**Comment by yvesgoeleven** [comment]
This is true, but it is due to Azure Service Bus behavior and not due to any library behavior.

If you want to solve this, set up the ASB topology in the following way:

- topic => subscription => forwarding rule => queue

Any receiver would then pull from the queue, instead of the subscription. And retries from dlq would be performed queue per queue instead of on the topic.

**Comment by eventsourcer** [comment]
thanks, I will try following this topology and see what will happen. was thinking this is happening downstream running all handlers the framework could find against a certain message.
